#' Build a small synthetic multi-batch Seurat object that mimics the
#' structure of the real prostate atlas closely enough to exercise
#' build_reference()/map_query(): multiple batches integrated with
#' IntegrateLayers(method = RPCAIntegration) into an "rpca" reduction, a
#' "umap.rpca" UMAP computed from it, and THEN a round of post-hoc cell
#' filtering (subsetting) performed *without* recomputing the UMAP -- this
#' reproduces the real-world scenario where umap.rpca coordinates cannot be
#' regenerated by simply re-running RunUMAP().
make_synthetic_atlas <- function(seed = 1, n_genes = 250, n_cells_per_batch = 200, npcs = 10) {
  set.seed(seed)
  n_batches <- 3
  n_cells <- n_cells_per_batch * n_batches
  counts <- matrix(stats::rpois(n_genes * n_cells, lambda = 3), nrow = n_genes, ncol = n_cells)
  rownames(counts) <- paste0("gene", seq_len(n_genes))
  colnames(counts) <- paste0("cell", seq_len(n_cells))

  seu <- SeuratObject::CreateSeuratObject(counts = counts)
  seu$batch <- rep(paste0("batch", seq_len(n_batches)), each = n_cells_per_batch)
  seu$sample.ID <- seu$batch
  seu[["RNA"]] <- split(seu[["RNA"]], f = seu$batch)

  seu <- Seurat::NormalizeData(seu, verbose = FALSE)
  seu <- Seurat::FindVariableFeatures(seu, nfeatures = min(150, n_genes), verbose = FALSE)
  seu <- Seurat::ScaleData(seu, verbose = FALSE)
  seu <- Seurat::RunPCA(seu, npcs = npcs, verbose = FALSE)
  seu <- Seurat::IntegrateLayers(
    seu,
    method = Seurat::RPCAIntegration,
    orig.reduction = "pca",
    new.reduction = "rpca",
    k.weight = min(50, n_cells_per_batch),
    verbose = FALSE
  )
  seu <- SeuratObject::JoinLayers(seu)
  seu <- Seurat::RunUMAP(seu, reduction = "rpca", dims = seq_len(npcs), reduction.name = "umap.rpca", verbose = FALSE)

  ## simulate manual cell-type annotation across 3 hierarchical levels
  base_type <- sample(c("Epithelial", "Immune", "Stromal"), n_cells, replace = TRUE)
  seu$celltype_manual_H1 <- base_type
  seu$celltype_manual_H2 <- paste0(base_type, "_sub", sample(1:2, n_cells, replace = TRUE))
  seu$celltype_manual_H3 <- paste0(seu$celltype_manual_H2, "_fine", sample(1:2, n_cells, replace = TRUE))
  ## a few NAs at the finest level, as in the real atlas
  na_idx <- sample(seq_len(n_cells), size = max(1, round(n_cells * 0.02)))
  seu$celltype_manual_H3[na_idx] <- NA

  ## simulate post-hoc low-quality-cell filtering AFTER umap.rpca was computed:
  ## subset the object without recomputing any reduction.
  set.seed(seed + 1)
  keep <- sort(sample(colnames(seu), size = round(n_cells * 0.85)))
  seu <- subset(seu, cells = keep)

  seu
}

#' Make a small, genuinely independent query Seurat object sharing the same
#' gene universe as a reference atlas (new simulated cells/counts, not a
#' subset of the reference).
make_synthetic_query <- function(gene_names, n_cells = 60, seed = 42) {
  set.seed(seed)
  n_genes <- length(gene_names)
  counts <- matrix(stats::rpois(n_genes * n_cells, lambda = 3), nrow = n_genes, ncol = n_cells)
  rownames(counts) <- gene_names
  colnames(counts) <- paste0("qcell", seq_len(n_cells))
  SeuratObject::CreateSeuratObject(counts = counts)
}

#' Tiny atlas-like Seurat for RCTD unit tests (no RPCA/UMAP needed).
make_synthetic_rctd_reference <- function(seed = 1,
                                          n_genes = 120,
                                          n_cells_per_type = 40,
                                          types = c("Epithelial", "Immune", "Stromal")) {
  set.seed(seed)
  n_types <- length(types)
  n_cells <- n_cells_per_type * n_types
  ## type-biased counts so RCTD can find DE genes
  counts <- matrix(0L, nrow = n_genes, ncol = n_cells)
  rownames(counts) <- paste0("gene", seq_len(n_genes))
  colnames(counts) <- paste0("cell", seq_len(n_cells))
  genes_per_type <- max(5L, floor(n_genes / (n_types + 1)))
  for (i in seq_len(n_types)) {
    cells <- seq.int((i - 1L) * n_cells_per_type + 1L, i * n_cells_per_type)
    marker <- seq.int((i - 1L) * genes_per_type + 1L, i * genes_per_type)
    counts[, cells] <- matrix(
      stats::rpois(n_genes * n_cells_per_type, lambda = 2),
      nrow = n_genes
    )
    counts[marker, cells] <- counts[marker, cells] +
      matrix(stats::rpois(length(marker) * n_cells_per_type, lambda = 20),
             nrow = length(marker))
  }
  seu <- SeuratObject::CreateSeuratObject(counts = counts)
  type_vec <- rep(types, each = n_cells_per_type)
  seu$celltype_manual_H1 <- type_vec
  seu$celltype_manual_H2 <- paste0(type_vec, "_sub", rep(1:2, length.out = n_cells))
  seu$celltype_manual_H3 <- paste0(seu$celltype_manual_H2, "_fine1")
  seu
}

#' Tiny spatial Seurat with explicit x/y coords for RCTD tests.
#' Also attaches a DimReduc named `"spatial"` so `coords = "spatial"` works.
make_synthetic_spatial <- function(gene_names, n_spots = 30, seed = 99) {
  set.seed(seed)
  n_genes <- length(gene_names)
  counts <- matrix(stats::rpois(n_genes * n_spots, lambda = 8), nrow = n_genes, ncol = n_spots)
  rownames(counts) <- gene_names
  colnames(counts) <- paste0("spot", seq_len(n_spots))
  seu <- SeuratObject::CreateSeuratObject(counts = counts, assay = "Spatial")
  coords <- data.frame(
    x = rep(seq_len(ceiling(sqrt(n_spots))), length.out = n_spots),
    y = rep(seq_len(ceiling(sqrt(n_spots))), each = ceiling(sqrt(n_spots)), length.out = n_spots),
    row.names = colnames(seu)
  )
  emb <- as.matrix(coords)
  colnames(emb) <- c("coords_1", "coords_2")
  seu[["spatial"]] <- SeuratObject::CreateDimReducObject(
    embeddings = emb,
    key = "coords_",
    assay = "Spatial"
  )
  list(seurat = seu, coords = coords)
}
